name: $(BuildDefinitionName)_$(date:yyyyMMdd)$(rev:.r)

trigger:
- main

stages :

  - stage: deployBicep
    jobs:
      - job: "BicepConfigure"
        steps:
 
          - task: Bash@3
            displayName: 'Bicep Build'
            inputs:
              targetType: inline
              script: |
                az bicep build --file $(System.DefaultWorkingDirectory)/BicepFiles/main.bicep
          - task: AzureCLI@2
            displayName: 'Deploy Bicep Configuration'
            inputs:
              azureSubscription: 'Bicep-RG'
              scriptType: bash
              scriptLocation: inlineScript
              addSpnToEnvironment: true
              inlineScript: |
                #!/bin/bash
                az deployment sub create --location WestUS --template-file main.bicep
