name: $(BuildDefinitionName)_$(date:yyyyMMdd)$(rev:.r)

trigger:
- none

pool:
  vmImage: 'ubuntu-latest'

stages :

  - stage: deployBicep
    jobs:
      - job: "BicepConfigure"
        steps:
                
          - task: AzureCLI@2
            displayName: 'Deploy Bicep Configuration'
            inputs:
              azureSubscription: 'Visual Studio Enterprise Subscription(88c4a907-c2bd-4880-b22f-79e78fe73484)'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                #!/bin/bash
                az group create -l westus -n bicep-rg 
                az bicep build --file $(System.DefaultWorkingDirectory)/BicepFiles/main.bicep
                az deployment sub create --l WestUS -f ./BicepFiles/AzurePolicy.bicep
              addSpnToEnvironment: true
